### ISSUE TITLE
issue in scan_analysis

### ISSUE THREAD

**Issue by skbarber** [GEECS-BELLA/GEECS-Plugins#75]
> 
> 
> This doesn't quite work right:
> 
> 
> 
>         if self.path_dict['cam_configs'].exists():
> 
>             self.camera_analysis_configs = self.load_camera_analysis_config()
> 
>             self.camera_analysis_settings = self.camera_analysis_configs[self.device_name]
> 
>         else:
> 
>             self.camera_analysis_configs = None
> 
>             self.camera_analysis_settings = None
> 
> 
> 
> If the self.device_name is not in the dict, this line will give an error and crash things:
> 
> self.camera_analysis_settings = self.camera_analysis_configs[self.device_name]
> 
> 
> 
> use the .get method for dicts, e.g. self.camera_analysis_configs.get(self.device_name, None), which allows to assign a value  (e.g. None) if the key doesn't exist in the dict. Then, I don't think you need any of the else statement either 

 _Originally posted by @skbarber in [3fe8d3d](https://github.com/GEECS-BELLA/GEECS-Plugins/commit/3fe8d3dac4eb1764a6c94e81331a198a7a2c0762#r149152125)_

**Comment by kjensen11** [comment]
Bug fix and response via pull request Bug fix in scan_analysis.py #76.
