### ISSUE TITLE
Remove calls to DataInterface from various places, as it no longer exists

### ISSUE THREAD

**Issue by TAU-Reinier** [GEECS-BELLA/GEECS-Plugins#95]
DataInterface was removed in 0c2ee62bdf38f0acd1c6bc222a64376e480d1190, but still 
has many references: 
- scan_analysis_routines.py
- rad2_single.py
- magnet_trajectory_calibrations.py
- visa_diode_calibration.py
- multiscan_analysis.py
- CameraImageAnalysis.py
- VisaEBeamAnalysis.py

Assignees: @kjensen11, Christopher Doss
Labels: 
Milestone: 
Projects: 

https://github.com/GEECS-BELLA/GEECS-Plugins/blob/9e26b2624f9bd4ddd0c95a6945dd477247c2f01e/ScanAnalysis/multiscan_analysis/Undulator/multiscan_analysis.py#L18-L19

**Comment by cedoss-lbl** [comment]
We went through and fixed the mentioned files in the recent commits to scan_analysis_dev branch
